enum GymLanguage { uk, en }

class GymLabels {
  const GymLabels(this.language);

  final GymLanguage language;

  static const _values = {
    GymLanguage.uk: {
      'base': 'ГОЛОВНА',
      'engine': 'АНАЛІТИКА',
      'analytics': 'Аналітика',
      'week': 'ТИЖДЕНЬ',
      'calendar': 'КАЛЕНДАР',
      'trained': 'ТРЕНУВАНЬ',
      'lastLiftShort': 'ОСТАННЯ',
      'nextUp': 'ДАЛІ',
      'startSession': 'ПОЧАТИ ТРЕНУВАННЯ',
      'lift': 'ПІДЙОМ',
      'activeSession': 'Активна сесія',
      'exercise': 'ВПРАВА',
      'kg': 'КГ',
      'reps': 'ПОВТОРИ',
      'smartHistory': 'РОЗУМНА ІСТОРІЯ',
      'noPreviousSets': 'Ще не було підходів',
      'unlockTargets': 'Запиши вправу, щоб бачити історію.',
      'logSet': 'ЗАПИСАТИ ПІДХІД',
      'finishSession': 'ЗАВЕРШИТИ ТРЕНУВАННЯ',
      'sets': 'ПІДХОДИ',
      'setsLogged': 'ПІДХОДІВ',
      'rest': 'ВІДПОЧИНОК',
      'restNotificationTitle': 'GymEngine: відпочинок закінчено',
      'restNotificationBody': 'Пора до наступного підходу.',
      'summary': 'ПІДСУМОК',
      'sessionComplete': 'Тренування закрито',
      'backToCore': 'НАЗАД ДО ГОЛОВНОЇ',
      'maxWeight': 'МАКС. ВАГА',
      'minWeight': 'МІН. ВАГА',
      'maxReps': 'МАКС. ПОВТ.',
      'minReps': 'МІН. ПОВТ.',
      'exerciseProgress': 'ПРОГРЕС ПО ВПРАВАХ',
      'noExerciseStats':
          'Запиши підхід, і тут буде мінімальна та максимальна вага.',
      'trainingCalendar': 'КАЛЕНДАР ТРЕНУВАНЬ',
      'monthView': 'МІСЯЦЬ З 1 ЧИСЛА',
      'monthStats': 'СТАТИСТИКА МІСЯЦЯ',
      'workoutsThisMonth': 'ТРЕНУВАНЬ ЦЬОГО МІСЯЦЯ',
      'liftsTracked': 'ВПРАВ ВІДСТЕЖУЄТЬСЯ',
      'bestWeight': 'НАЙБІЛЬША ВАГА',
      'previousMonth': 'МИНУЛИЙ',
      'nextMonth': 'НАСТУПНИЙ',
      'trainingDay': 'ДЕНЬ ТРЕНУВАННЯ',
      'selectTrainingDay': 'Натисни на підсвічений день, щоб побачити вправи.',
      'noDayDetails': 'У цей день тренування не записано.',
      'profile': 'ПРОФІЛЬ',
      'profileTitle': 'МІЙ ПРОФІЛЬ',
      'settings': 'НАЛАШТУВАННЯ',
      'lightTheme': 'СВІТЛА',
      'darkTheme': 'ТЕМНА',
      'profileName': 'Імʼя',
      'bodyWeight': 'Вага тіла',
      'saveProfile': 'ЗБЕРЕГТИ ПРОФІЛЬ',
      'profileSaved': 'Профіль збережено',
      'profileEmptyName': 'Спортсменка',
      'email': 'Пошта',
      'password': 'Пароль',
      'repeatPassword': 'Повтор паролю',
      'register': 'РЕЄСТРАЦІЯ',
      'login': 'ВХІД',
      'logout': 'ВИЙТИ',
      'authLoggedOut': 'Вийшла з акаунта',
      'authFailed': 'Авторизація не вдалась. Перевір пошту, пароль і сервер.',
      'verifyEmail': 'ПІДТВЕРДИ ПОШТУ',
      'emailCode': 'Код з пошти',
      'sendCode': 'НАДІСЛАТИ КОД',
      'codeSent': 'Код надіслано на пошту',
      'confirmEmail': 'ПІДТВЕРДИТИ ПОШТУ',
      'forgotPassword': 'Забула пароль?',
      'resetPassword': 'СКИНУТИ ПАРОЛЬ',
      'newPassword': 'Новий пароль',
      'resetCodeSent': 'Код для скидання паролю надіслано',
      'backToLogin': 'Назад до входу',
      'trainingData': 'ТРЕНУВАЛЬНІ ДАНІ',
      'cancelSet': 'СКАСУВАТИ',
      'setLabel': 'Підхід',
      'restControl': 'ВІДПОЧИНОК',
      'shortSeconds': 'с',
      'shortMinutes': 'хв',
      'secondsUnit': 'СЕК',
      'minutesUnit': 'ХВ',
      'programDay': 'День',
      'programDayShort': 'ДЕНЬ',
      'emptyDayShort': 'Порожній',
      'addProgramDay': 'ДОДАТИ ДЕНЬ',
      'createDay': 'СТВОРИТИ ДЕНЬ',
      'editDay': 'РЕДАГУВАТИ ДЕНЬ',
      'deleteDay': 'ВИДАЛИТИ ДЕНЬ',
      'deleteDayConfirm':
          'Цей день зникне з програми. Наступні дні автоматично зсунуться.',
      'deleteTrainingDay': 'ВИДАЛИТИ ТРЕНУВАННЯ',
      'deleteTrainingDayConfirm':
          'Це видалить записане тренування з аналітики за цей день.',
      'delete': 'ВИДАЛИТИ',
      'saveDay': 'ЗБЕРЕГТИ ДЕНЬ',
      'cancel': 'СКАСУВАТИ',
      'dayName': 'Назва дня',
      'addExercise': 'ДОДАТИ ВПРАВУ',
      'quickAdd': 'ШВИДКЕ ДОДАВАННЯ',
      'customExercise': 'СВОЯ ВПРАВА',
      'exerciseName': 'Назва вправи',
      'muscleGroup': 'Група мʼязів',
      'exerciseComment': 'Коментар до вправи',
      'editExercise': 'Редагувати вправу',
      'deleteExercise': 'Видалити вправу',
      'planOrder': 'ПОРЯДОК ДНЯ',
      'targetSets': 'ПІДХОДІВ',
      'targetReps': 'ПОВТОРІВ',
      'setsSmall': 'підх.',
      'repsSmall': 'повт.',
      'exerciseSettings': 'НАЛАШТУВАННЯ ВПРАВИ',
      'save': 'ЗБЕРЕГТИ',
      'sessionPlan': 'ПЛАН СЕСІЇ',
      'nextExercise': 'НАСТУПНА ВПРАВА',
      'previousExercise': 'НАЗАД',
      'back': 'НАЗАД',
      'done': 'ГОТОВО',
      'loading': 'Завантаження...',
      'emptyDayTitle': 'День ще порожній',
      'emptyDaySubtitle': 'Створи план і запускай тренування по порядку.',
      'plannedExercises': 'ПЛАН ВПРАВ',
      'lastLift': 'Остання вправа',
      'noSets': 'Підходів ще немає.',
    },
    GymLanguage.en: {
      'base': 'CORE',
      'engine': 'ANALYTICS',
      'analytics': 'Analytics',
      'week': 'WEEK',
      'calendar': 'CALENDAR',
      'trained': 'SESSIONS',
      'lastLiftShort': 'LAST',
      'nextUp': 'NEXT UP',
      'startSession': 'START SESSION',
      'lift': 'THE LIFT',
      'activeSession': 'Active Session',
      'exercise': 'EXERCISE',
      'kg': 'KG',
      'reps': 'REPS',
      'smartHistory': 'SMART HISTORY',
      'noPreviousSets': 'No previous sets',
      'unlockTargets': 'Log this lift once to unlock history.',
      'logSet': 'LOG SET',
      'finishSession': 'FINISH SESSION',
      'sets': 'SETS',
      'setsLogged': 'SETS',
      'rest': 'REST',
      'restNotificationTitle': 'GymEngine: rest is over',
      'restNotificationBody': 'Time for the next set.',
      'summary': 'SUMMARY',
      'sessionComplete': 'Session Complete',
      'backToCore': 'BACK TO CORE',
      'maxWeight': 'MAX WEIGHT',
      'minWeight': 'MIN WEIGHT',
      'maxReps': 'MAX REPS',
      'minReps': 'MIN REPS',
      'exerciseProgress': 'LIFT PROGRESS',
      'noExerciseStats': 'Log a set to see min and max weight here.',
      'trainingCalendar': 'TRAINING CALENDAR',
      'monthView': 'MONTH FROM DAY 1',
      'monthStats': 'MONTH STATS',
      'workoutsThisMonth': 'WORKOUTS THIS MONTH',
      'liftsTracked': 'LIFTS TRACKED',
      'bestWeight': 'BEST WEIGHT',
      'previousMonth': 'PREV',
      'nextMonth': 'NEXT',
      'trainingDay': 'TRAINING DAY',
      'selectTrainingDay': 'Tap a highlighted day to see lifts.',
      'noDayDetails': 'No workout logged on this day.',
      'profile': 'PROFILE',
      'profileTitle': 'MY PROFILE',
      'settings': 'SETTINGS',
      'lightTheme': 'LIGHT',
      'darkTheme': 'DARK',
      'profileName': 'Name',
      'bodyWeight': 'Body weight',
      'saveProfile': 'SAVE PROFILE',
      'profileSaved': 'Profile saved',
      'profileEmptyName': 'Athlete',
      'email': 'Email',
      'password': 'Password',
      'repeatPassword': 'Repeat password',
      'register': 'REGISTER',
      'login': 'LOGIN',
      'logout': 'LOG OUT',
      'authLoggedOut': 'Signed out',
      'authFailed': 'Auth failed. Check email, password, and server.',
      'verifyEmail': 'VERIFY EMAIL',
      'emailCode': 'Email code',
      'sendCode': 'SEND CODE',
      'codeSent': 'Code sent to email',
      'confirmEmail': 'CONFIRM EMAIL',
      'forgotPassword': 'Forgot password?',
      'resetPassword': 'RESET PASSWORD',
      'newPassword': 'New password',
      'resetCodeSent': 'Password reset code sent',
      'backToLogin': 'Back to login',
      'trainingData': 'TRAINING DATA',
      'cancelSet': 'UNDO',
      'setLabel': 'Set',
      'restControl': 'REST',
      'shortSeconds': 's',
      'shortMinutes': 'min',
      'secondsUnit': 'SEC',
      'minutesUnit': 'MIN',
      'programDay': 'Day',
      'programDayShort': 'DAY',
      'emptyDayShort': 'Empty',
      'addProgramDay': 'ADD DAY',
      'createDay': 'CREATE DAY',
      'editDay': 'EDIT DAY',
      'deleteDay': 'DELETE DAY',
      'deleteDayConfirm':
          'This day will be removed from the program. Following days will shift in order.',
      'deleteTrainingDay': 'DELETE WORKOUT',
      'deleteTrainingDayConfirm':
          'This removes the logged workout from analytics for this day.',
      'delete': 'DELETE',
      'saveDay': 'SAVE DAY',
      'cancel': 'CANCEL',
      'dayName': 'Day name',
      'addExercise': 'ADD LIFT',
      'quickAdd': 'QUICK ADD',
      'customExercise': 'CUSTOM LIFT',
      'exerciseName': 'Exercise name',
      'muscleGroup': 'Muscle group',
      'exerciseComment': 'Exercise note',
      'editExercise': 'Edit lift',
      'deleteExercise': 'Delete lift',
      'planOrder': 'DAY ORDER',
      'targetSets': 'SETS',
      'targetReps': 'REPS',
      'setsSmall': 'sets',
      'repsSmall': 'reps',
      'exerciseSettings': 'LIFT SETTINGS',
      'save': 'SAVE',
      'sessionPlan': 'SESSION PLAN',
      'nextExercise': 'NEXT LIFT',
      'previousExercise': 'BACK',
      'back': 'BACK',
      'done': 'DONE',
      'loading': 'Loading...',
      'emptyDayTitle': 'Day is empty',
      'emptyDaySubtitle': 'Create a plan and run the lifts in order.',
      'plannedExercises': 'PLANNED LIFTS',
      'lastLift': 'Last lift',
      'noSets': 'No sets logged yet.',
    },
  };

  static const _exerciseNames = {
    GymLanguage.uk: {
      'bench_press': 'Жим лежачи',
      'incline_press': 'Жим під кутом',
      'dumbbell_fly': 'Розведення гантелей',
      'squat': 'Присідання',
      'leg_press': 'Жим ногами',
      'lunge': 'Випади',
      'leg_extension': 'Розгинання ніг',
      'deadlift': 'Станова тяга',
      'romanian_deadlift': 'Румунська тяга',
      'hip_thrust': 'Хіп траст',
      'glute_bridge': 'Сідничний міст',
      'leg_curl': 'Згинання ніг',
      'overhead_press': 'Армійський жим',
      'lateral_raise': 'Підйом гантелей в сторони',
      'rear_delt_fly': 'Задня дельта',
      'barbell_row': 'Тяга штанги',
      'pull_up': 'Підтягування',
      'lat_pulldown': 'Тяга верхнього блоку',
      'seated_row': 'Горизонтальна тяга',
      'biceps_curl': 'Підйом на біцепс',
      'hammer_curl': 'Молотки',
      'triceps_pushdown': 'Розгинання на трицепс',
      'skull_crusher': 'Французький жим',
      'plank': 'Планка',
      'cable_crunch': 'Скручування в блоці',
    },
    GymLanguage.en: {
      'bench_press': 'Bench Press',
      'incline_press': 'Incline Press',
      'dumbbell_fly': 'Dumbbell Fly',
      'squat': 'Squat',
      'leg_press': 'Leg Press',
      'lunge': 'Lunge',
      'leg_extension': 'Leg Extension',
      'deadlift': 'Deadlift',
      'romanian_deadlift': 'Romanian Deadlift',
      'hip_thrust': 'Hip Thrust',
      'glute_bridge': 'Glute Bridge',
      'leg_curl': 'Leg Curl',
      'overhead_press': 'Overhead Press',
      'lateral_raise': 'Lateral Raise',
      'rear_delt_fly': 'Rear Delt Fly',
      'barbell_row': 'Barbell Row',
      'pull_up': 'Pull-Up',
      'lat_pulldown': 'Lat Pulldown',
      'seated_row': 'Seated Row',
      'biceps_curl': 'Biceps Curl',
      'hammer_curl': 'Hammer Curl',
      'triceps_pushdown': 'Triceps Pushdown',
      'skull_crusher': 'Skull Crusher',
      'plank': 'Plank',
      'cable_crunch': 'Cable Crunch',
    },
  };

  static const _muscleNames = {
    GymLanguage.uk: {
      'Chest': 'Груди',
      'Quads': 'Квадрицепси',
      'Posterior': 'Задній ланцюг',
      'Shoulders': 'Плечі',
      'Back': 'Спина',
      'Glutes': 'Сідниці',
      'Hamstrings': 'Біцепс стегна',
      'Biceps': 'Біцепс',
      'Triceps': 'Трицепс',
      'Core': 'Прес',
      'Custom': 'Свої',
      'Unknown': 'Невідомо',
    },
    GymLanguage.en: {
      'Chest': 'Chest',
      'Quads': 'Quads',
      'Posterior': 'Posterior',
      'Shoulders': 'Shoulders',
      'Back': 'Back',
      'Glutes': 'Glutes',
      'Hamstrings': 'Hamstrings',
      'Biceps': 'Biceps',
      'Triceps': 'Triceps',
      'Core': 'Core',
      'Custom': 'Custom',
      'Unknown': 'Unknown',
    },
  };

  String t(String key) => _values[language]![key] ?? key;

  String exerciseName(String id, String fallback) {
    return _exerciseNames[language]![id] ?? fallback;
  }

  String muscleName(String muscle) {
    return _muscleNames[language]![muscle] ?? muscle;
  }
}
