import 'exercise_name_translator.dart';

enum GymLanguage { uk, en }

class GymLabels {
  const GymLabels(this.language);

  final GymLanguage language;

  static const _values = {
    GymLanguage.uk: {
      'base': 'ГОЛОВНА',
      'engine': 'ПРОГРЕС',
      'analytics': 'Прогрес',
      'week': 'ТИЖДЕНЬ',
      'calendar': 'КАЛЕНДАР',
      'trained': 'ТРЕНУВАНЬ',
      'lastLiftShort': 'ОСТАННЯ',
      'nextUp': 'ДАЛІ',
      'startSession': 'ПОЧАТИ ТРЕНУВАННЯ',
      'lift': 'ПІДЙОМ',
      'activeSession': 'Активна сесія',
      'exercise': 'ВПРАВА',
      'kg': 'КГ',
      'reps': 'ПОВТОРИ',
      'smartHistory': 'РОЗУМНА ІСТОРІЯ',
      'noPreviousSets': 'Ще не було підходів',
      'unlockTargets': 'Запиши вправу, щоб бачити історію.',
      'logSet': 'ЗАПИСАТИ ПІДХІД',
      'finishSession': 'ЗАВЕРШИТИ ТРЕНУВАННЯ',
      'sets': 'ПІДХОДИ',
      'setsLogged': 'ПІДХОДІВ',
      'rest': 'ВІДПОЧИНОК',
      'restNotificationTitle': 'GymEngine: відпочинок закінчено',
      'restNotificationBody': 'Пора до наступного підходу.',
      'summary': 'ПІДСУМОК',
      'sessionComplete': 'Тренування закрито',
      'backToCore': 'НАЗАД ДО ГОЛОВНОЇ',
      'maxWeight': 'МАКС. ВАГА',
      'minWeight': 'МІН. ВАГА',
      'maxReps': 'МАКС. ПОВТ.',
      'minReps': 'МІН. ПОВТ.',
      'exerciseProgress': 'ПРОГРЕС ПО ВПРАВАХ',
      'noExerciseStats':
          'Запиши підхід, і тут буде мінімальна та максимальна вага.',
      'trainingCalendar': 'КАЛЕНДАР ТРЕНУВАНЬ',
      'monthView': 'МІСЯЦЬ З 1 ЧИСЛА',
      'monthStats': 'СТАТИСТИКА МІСЯЦЯ',
      'workoutsThisMonth': 'ТРЕНУВАНЬ ЦЬОГО МІСЯЦЯ',
      'liftsTracked': 'ВПРАВ ВІДСТЕЖУЄТЬСЯ',
      'bestWeight': 'НАЙБІЛЬША ВАГА',
      'previousMonth': 'МИНУЛИЙ',
      'nextMonth': 'НАСТУПНИЙ',
      'trainingDay': 'ДЕНЬ ТРЕНУВАННЯ',
      'selectTrainingDay': 'Натисни на підсвічений день, щоб побачити вправи.',
      'noDayDetails': 'У цей день тренування не записано.',
      'profile': 'ПРОФІЛЬ',
      'profileTitle': 'МІЙ ПРОФІЛЬ',
      'settings': 'НАЛАШТУВАННЯ',
      'lightTheme': 'СВІТЛА',
      'darkTheme': 'ТЕМНА',
      'profileName': 'Імʼя',
      'bodyWeight': 'Вага тіла',
      'saveProfile': 'ЗБЕРЕГТИ ПРОФІЛЬ',
      'profileSaved': 'Профіль збережено',
      'profileEmptyName': 'Спортсменка',
      'email': 'Пошта',
      'password': 'Пароль',
      'repeatPassword': 'Повтор паролю',
      'register': 'РЕЄСТРАЦІЯ',
      'login': 'ВХІД',
      'logout': 'ВИЙТИ',
      'authLoggedOut': 'Вийшла з акаунта',
      'authFailed': 'Авторизація не вдалась. Перевір пошту і пароль.',
      'verifyEmail': 'ПІДТВЕРДИ ПОШТУ',
      'emailCode': 'Код з пошти',
      'sendCode': 'НАДІСЛАТИ КОД',
      'codeSent': 'Код надіслано на пошту',
      'confirmEmail': 'ПІДТВЕРДИТИ ПОШТУ',
      'forgotPassword': 'Забули пароль?',
      'resetPassword': 'СКИНУТИ ПАРОЛЬ',
      'newPassword': 'Новий пароль',
      'resetCodeSent': 'Код для скидання паролю надіслано',
      'backToLogin': 'Назад до входу',
      'trainingData': 'ТРЕНУВАЛЬНІ ДАНІ',
      'cancelSet': 'СКАСУВАТИ',
      'setLabel': 'Підхід',
      'restControl': 'ВІДПОЧИНОК',
      'shortSeconds': 'с',
      'shortMinutes': 'хв',
      'secondsUnit': 'СЕК',
      'minutesUnit': 'ХВ',
      'programDay': 'День',
      'programDayShort': 'ДЕНЬ',
      'emptyDayShort': 'Порожній',
      'addProgramDay': 'ДОДАТИ ДЕНЬ',
      'createDay': 'СТВОРИТИ ДЕНЬ',
      'editDay': 'РЕДАГУВАТИ ДЕНЬ',
      'deleteDay': 'ВИДАЛИТИ ДЕНЬ',
      'deleteDayConfirm':
          'Цей день зникне з програми. Наступні дні автоматично зсунуться.',
      'deleteTrainingDay': 'ВИДАЛИТИ ТРЕНУВАННЯ',
      'deleteTrainingDayConfirm':
          'Це видалить записане тренування з аналітики за цей день.',
      'delete': 'ВИДАЛИТИ',
      'saveDay': 'ЗБЕРЕГТИ ДЕНЬ',
      'cancel': 'СКАСУВАТИ',
      'dayName': 'Назва дня',
      'addExercise': 'ДОДАТИ ВПРАВУ',
      'quickAdd': 'ШВИДКЕ ДОДАВАННЯ',
      'customExercise': 'СВОЯ ВПРАВА',
      'exerciseName': 'Назва вправи',
      'muscleGroup': 'Група мʼязів',
      'exerciseComment': 'Коментар до вправи',
      'editExercise': 'Редагувати вправу',
      'deleteExercise': 'Видалити вправу',
      'planOrder': 'ПОРЯДОК ДНЯ',
      'targetSets': 'ПІДХОДІВ',
      'targetReps': 'ПОВТОРІВ',
      'setsSmall': 'підх.',
      'repsSmall': 'повт.',
      'exerciseSettings': 'НАЛАШТУВАННЯ ВПРАВИ',
      'save': 'ЗБЕРЕГТИ',
      'sessionPlan': 'ПЛАН СЕСІЇ',
      'nextExercise': 'НАСТУПНА ВПРАВА',
      'previousExercise': 'НАЗАД',
      'back': 'НАЗАД',
      'done': 'ГОТОВО',
      'loading': 'Завантаження...',
      'emptyDayTitle': 'День ще порожній',
      'emptyDaySubtitle': 'Створи план і запускай тренування по порядку.',
      'plannedExercises': 'ПЛАН ВПРАВ',
      'lastLift': 'Остання вправа',
      'noSets': 'Підходів ще немає.',
      'workoutRunning': 'ТРЕНУВАННЯ ТРИВАЄ',
      'continueSession': 'ПРОДОВЖИТИ',
      'stopSession': 'ПРИПИНИТИ',
      'stopSessionConfirmTitle': 'Припинити тренування?',
      'stopSessionConfirmBody':
          'Записані підходи залишаться в базі, але активна сесія закриється.',
      'elapsed': 'ЧАС',
      'ongoingNotificationTitle': 'GymEngine: тренування триває',
      'ongoingNotificationBody': 'Натисни, щоб повернутися до активної сесії.',
      'overview': 'Огляд',
      'exercises': 'Вправи',
      'measurements': 'Вимірювання',
      'photos': 'Фото',
      'weeklyWorkouts': 'ТРЕНУВАНЬ ЦЬОГО ТИЖНЯ',
      'totalTrainingTime': 'ЧАС У ТРЕНУВАННЯХ',
      'streak': 'СЕРІЯ ДНІВ',
      'days': 'дн.',
      'muscleFocus': 'ЦЬОГО МІСЯЦЯ',
      'muscleFocusHint': 'Дивись, які мʼязи отримують більше роботи.',
      'attentionHint': 'Слабші сектори підкажуть, що варто підтягнути.',
      'noDataYet': 'Запиши тренування, і тут зʼявиться мʼязовий фокус.',
      'challenges': 'ЧЕЛЕНДЖІ',
      'more': 'Більше',
      'allChallenges': 'Усі челенджі',
      'reward': 'Нагорода',
      'completed': 'Виконано',
      'streakChallenge': 'Тримай серію тренувань',
      'balanceChallenge': 'Добий найтемніший сектор мʼязів',
      'weeklyChallenge': 'Закрий 3 тренування за тиждень',
      'timeChallenge': 'Набери 3 години силової роботи',
      'photoProgressTitle': 'ФОТО ПРОГРЕСУ',
      'photoProgressHint':
          'Фіксуй форму по датах, щоб бачити зміни без здогадок.',
      'addProgressPhoto': 'ДОДАТИ ФОТО',
      'deleteProgressPhoto': 'ВИДАЛИТИ ФОТО',
      'progressPhotoAdded': 'Фото прогресу збережено',
      'progressPhotoDeleted': 'Фото видалено',
      'noProgressPhotos': 'Фото ще немає. Додай перший знімок прогресу.',
      'photoDate': 'Дата фото',
      'photoComment': 'Коментар до фото',
      'photoCommentHint':
          'Наприклад: ранок, після тренування, вага, самопочуття...',
      'photoCommentRequired': 'Додай короткий коментар до фото',
      'savePhoto': 'ЗБЕРЕГТИ ФОТО',
      'openPhoto': 'Відкрити фото',
      'photoPlaceholder': 'Фото прогресу додамо наступним вузлом.',
      'exerciseSearch': 'Пошук вправи',
      'exerciseLibrary': 'БІБЛІОТЕКА ВПРАВ',
      'allMuscles': 'Всі',
      'add': 'ДОДАТИ',
      'catalogHint': 'Шукай по назві або мʼязах. Не треба забивати все вручну.',
      'todayFocus': 'Фокус дня',
      'plannedCount': 'вправ у плані',
      'homeChallengeTitle': 'СЬОГОДНІШНІЙ ВИКЛИК',
      'homeChallengeBody': 'Закрий план без пропусків і збережи серію.',
      'nextWorkout': 'НАСТУПНЕ ТРЕНУВАННЯ',
    },
    GymLanguage.en: {
      'base': 'CORE',
      'engine': 'PROGRESS',
      'analytics': 'Progress',
      'week': 'WEEK',
      'calendar': 'CALENDAR',
      'trained': 'SESSIONS',
      'lastLiftShort': 'LAST',
      'nextUp': 'NEXT UP',
      'startSession': 'START SESSION',
      'lift': 'THE LIFT',
      'activeSession': 'Active Session',
      'exercise': 'EXERCISE',
      'kg': 'KG',
      'reps': 'REPS',
      'smartHistory': 'SMART HISTORY',
      'noPreviousSets': 'No previous sets',
      'unlockTargets': 'Log this lift once to unlock history.',
      'logSet': 'LOG SET',
      'finishSession': 'FINISH SESSION',
      'sets': 'SETS',
      'setsLogged': 'SETS',
      'rest': 'REST',
      'restNotificationTitle': 'GymEngine: rest is over',
      'restNotificationBody': 'Time for the next set.',
      'summary': 'SUMMARY',
      'sessionComplete': 'Session Complete',
      'backToCore': 'BACK TO CORE',
      'maxWeight': 'MAX WEIGHT',
      'minWeight': 'MIN WEIGHT',
      'maxReps': 'MAX REPS',
      'minReps': 'MIN REPS',
      'exerciseProgress': 'LIFT PROGRESS',
      'noExerciseStats': 'Log a set to see min and max weight here.',
      'trainingCalendar': 'TRAINING CALENDAR',
      'monthView': 'MONTH FROM DAY 1',
      'monthStats': 'MONTH STATS',
      'workoutsThisMonth': 'WORKOUTS THIS MONTH',
      'liftsTracked': 'LIFTS TRACKED',
      'bestWeight': 'BEST WEIGHT',
      'previousMonth': 'PREV',
      'nextMonth': 'NEXT',
      'trainingDay': 'TRAINING DAY',
      'selectTrainingDay': 'Tap a highlighted day to see lifts.',
      'noDayDetails': 'No workout logged on this day.',
      'profile': 'PROFILE',
      'profileTitle': 'MY PROFILE',
      'settings': 'SETTINGS',
      'lightTheme': 'LIGHT',
      'darkTheme': 'DARK',
      'profileName': 'Name',
      'bodyWeight': 'Body weight',
      'saveProfile': 'SAVE PROFILE',
      'profileSaved': 'Profile saved',
      'profileEmptyName': 'Athlete',
      'email': 'Email',
      'password': 'Password',
      'repeatPassword': 'Repeat password',
      'register': 'REGISTER',
      'login': 'LOGIN',
      'logout': 'LOG OUT',
      'authLoggedOut': 'Signed out',
      'authFailed': 'Auth failed. Check email and password.',
      'verifyEmail': 'VERIFY EMAIL',
      'emailCode': 'Email code',
      'sendCode': 'SEND CODE',
      'codeSent': 'Code sent to email',
      'confirmEmail': 'CONFIRM EMAIL',
      'forgotPassword': 'Forgot password?',
      'resetPassword': 'RESET PASSWORD',
      'newPassword': 'New password',
      'resetCodeSent': 'Password reset code sent',
      'backToLogin': 'Back to login',
      'trainingData': 'TRAINING DATA',
      'cancelSet': 'UNDO',
      'setLabel': 'Set',
      'restControl': 'REST',
      'shortSeconds': 's',
      'shortMinutes': 'min',
      'secondsUnit': 'SEC',
      'minutesUnit': 'MIN',
      'programDay': 'Day',
      'programDayShort': 'DAY',
      'emptyDayShort': 'Empty',
      'addProgramDay': 'ADD DAY',
      'createDay': 'CREATE DAY',
      'editDay': 'EDIT DAY',
      'deleteDay': 'DELETE DAY',
      'deleteDayConfirm':
          'This day will be removed from the program. Following days will shift in order.',
      'deleteTrainingDay': 'DELETE WORKOUT',
      'deleteTrainingDayConfirm':
          'This removes the logged workout from analytics for this day.',
      'delete': 'DELETE',
      'saveDay': 'SAVE DAY',
      'cancel': 'CANCEL',
      'dayName': 'Day name',
      'addExercise': 'ADD LIFT',
      'quickAdd': 'QUICK ADD',
      'customExercise': 'CUSTOM LIFT',
      'exerciseName': 'Exercise name',
      'muscleGroup': 'Muscle group',
      'exerciseComment': 'Exercise note',
      'editExercise': 'Edit lift',
      'deleteExercise': 'Delete lift',
      'planOrder': 'DAY ORDER',
      'targetSets': 'SETS',
      'targetReps': 'REPS',
      'setsSmall': 'sets',
      'repsSmall': 'reps',
      'exerciseSettings': 'LIFT SETTINGS',
      'save': 'SAVE',
      'sessionPlan': 'SESSION PLAN',
      'nextExercise': 'NEXT LIFT',
      'previousExercise': 'BACK',
      'back': 'BACK',
      'done': 'DONE',
      'loading': 'Loading...',
      'emptyDayTitle': 'Day is empty',
      'emptyDaySubtitle': 'Create a plan and run the lifts in order.',
      'plannedExercises': 'PLANNED LIFTS',
      'lastLift': 'Last lift',
      'noSets': 'No sets logged yet.',
      'workoutRunning': 'WORKOUT IN PROGRESS',
      'continueSession': 'CONTINUE',
      'stopSession': 'STOP',
      'stopSessionConfirmTitle': 'Stop this workout?',
      'stopSessionConfirmBody':
          'Logged sets will stay in the database, but the active session will close.',
      'elapsed': 'TIME',
      'ongoingNotificationTitle': 'GymEngine: workout in progress',
      'ongoingNotificationBody': 'Tap to return to the active session.',
      'overview': 'Overview',
      'exercises': 'Exercises',
      'measurements': 'Measurements',
      'photos': 'Photos',
      'weeklyWorkouts': 'WORKOUTS THIS WEEK',
      'totalTrainingTime': 'TRAINING TIME',
      'streak': 'DAY STREAK',
      'days': 'd',
      'muscleFocus': 'THIS MONTH',
      'muscleFocusHint': 'See which muscles get the most work.',
      'attentionHint': 'Darker sectors show what needs more attention.',
      'noDataYet': 'Log a workout to unlock muscle focus.',
      'challenges': 'CHALLENGES',
      'more': 'More',
      'allChallenges': 'All challenges',
      'reward': 'Reward',
      'completed': 'Completed',
      'streakChallenge': 'Keep your workout streak alive',
      'balanceChallenge': 'Train the darkest muscle sector',
      'weeklyChallenge': 'Complete 3 workouts this week',
      'timeChallenge': 'Reach 3 hours of strength work',
      'photoProgressTitle': 'PROGRESS PHOTOS',
      'photoProgressHint':
          'Track your physique by date and see changes without guessing.',
      'addProgressPhoto': 'ADD PHOTO',
      'deleteProgressPhoto': 'DELETE PHOTO',
      'progressPhotoAdded': 'Progress photo saved',
      'progressPhotoDeleted': 'Photo deleted',
      'noProgressPhotos': 'No photos yet. Add your first progress shot.',
      'photoDate': 'Photo date',
      'photoComment': 'Photo comment',
      'photoCommentHint':
          'Example: morning, after training, body weight, how you feel...',
      'photoCommentRequired': 'Add a short comment to the photo',
      'savePhoto': 'SAVE PHOTO',
      'openPhoto': 'Open photo',
      'photoPlaceholder': 'Progress photos come in the next build.',
      'exerciseSearch': 'Search exercise',
      'exerciseLibrary': 'EXERCISE LIBRARY',
      'allMuscles': 'All',
      'add': 'ADD',
      'catalogHint': 'Search by name or muscle. No manual typing needed.',
      'todayFocus': 'Day focus',
      'plannedCount': 'lifts planned',
      'homeChallengeTitle': 'TODAY CHALLENGE',
      'homeChallengeBody': 'Finish the plan without skips and keep the streak.',
      'nextWorkout': 'NEXT WORKOUT',
    },
  };

  static const _exerciseNames = {
    GymLanguage.uk: {
      'bench_press': 'Жим лежачи',
      'barbell_bench_press': 'Жим штанги лежачи',
      'dumbbell_bench_press': 'Жим гантелей лежачи',
      'incline_press': 'Жим під кутом',
      'incline_bench_press': 'Жим під кутом',
      'dumbbell_incline_bench_press': 'Жим гантелей під кутом',
      'decline_bench_press': 'Жим на похилій вниз',
      'chest_dip': 'Віджимання на брусах для грудей',
      'push_up': 'Віджимання',
      'decline_push_up': 'Віджимання з ногами вище',
      'lever_chest_press': 'Жим у тренажері',
      'pec_deck_fly': 'Пек-дек',
      'dumbbell_fly': 'Розведення гантелей',
      'cable_fly': 'Кросовер',
      'cable_middle_fly': 'Кросовер на середину грудей',
      'squat': 'Присідання',
      'front_squat': 'Фронтальні присідання',
      'goblet_squat': 'Гоблет присідання',
      'smith_squat': 'Присідання в Сміті',
      'hack_squat': 'Гак-присідання',
      'bulgarian_split_squat': 'Болгарські випади',
      'walking_lunge': 'Випади в ходьбі',
      'leg_press': 'Жим ногами',
      'sled_45_leg_press': 'Жим ногами 45 градусів',
      'lunge': 'Випади',
      'leg_extension': 'Розгинання ніг',
      'lever_leg_extension': 'Розгинання ніг у тренажері',
      'deadlift': 'Станова тяга',
      'straight_leg_deadlift': 'Тяга на прямих ногах',
      'sumo_deadlift': 'Сумо тяга',
      'good_morning': 'Гуд морнінг',
      'back_extension': 'Гіперекстензія',
      'romanian_deadlift': 'Румунська тяга',
      'hip_thrust': 'Хіп траст',
      'single_leg_hip_thrust': 'Хіп траст однією ногою',
      'glute_bridge': 'Сідничний міст',
      'cable_kickback': 'Відведення ноги в кросовері',
      'hip_abduction': 'Відведення стегна',
      'lever_hip_abduction': 'Відведення стегна в тренажері',
      'leg_curl': 'Згинання ніг',
      'lying_leg_curl': 'Згинання ніг лежачи',
      'seated_leg_curl': 'Згинання ніг сидячи',
      'nordic_curl': 'Нордичні згинання',
      'standing_calf_raise': 'Підйом на ікри стоячи',
      'seated_calf_raise': 'Підйом на ікри сидячи',
      'smith_calf_raise': 'Ікри в Сміті',
      'overhead_press': 'Армійський жим',
      'military_press': 'Військовий жим',
      'seated_shoulder_press': 'Жим на плечі сидячи',
      'dumbbell_shoulder_press': 'Жим гантелей на плечі',
      'arnold_press': 'Жим Арнольда',
      'lateral_raise': 'Підйом гантелей в сторони',
      'seated_lateral_raise': 'Підйом в сторони сидячи',
      'front_raise': 'Підйом перед собою',
      'rear_delt_fly': 'Задня дельта',
      'face_pull': 'Тяга до обличчя',
      'upright_row': 'Тяга до підборіддя',
      'barbell_row': 'Тяга штанги',
      'bent_over_row': 'Тяга в нахилі',
      'one_arm_row': 'Тяга однією рукою',
      't_bar_row': 'Тяга Т-грифа',
      'pull_up': 'Підтягування',
      'chin_up': 'Підтягування зворотним хватом',
      'lat_pulldown': 'Тяга верхнього блоку',
      'v_bar_pulldown': 'Тяга V-рукояті',
      'straight_arm_pulldown': 'Тяга прямими руками',
      'seated_row': 'Горизонтальна тяга',
      'low_seated_row': 'Нижня горизонтальна тяга',
      'shrug': 'Шраги',
      'dumbbell_shrug': 'Шраги з гантелями',
      'biceps_curl': 'Підйом на біцепс',
      'barbell_curl': 'Підйом штанги на біцепс',
      'hammer_curl': 'Молотки',
      'preacher_curl': 'Підйом на лаві Скотта',
      'incline_dumbbell_curl': 'Біцепс на похилій лаві',
      'cable_biceps_curl': 'Біцепс у кросовері',
      'concentration_curl': 'Концентрований підйом',
      'triceps_pushdown': 'Розгинання на трицепс',
      'rope_pushdown': 'Канат на трицепс',
      'skull_crusher': 'Французький жим',
      'overhead_triceps_extension': 'Розгинання трицепса над головою',
      'close_grip_push_up': 'Віджимання вузьким хватом',
      'triceps_dip': 'Віджимання на трицепс',
      'weighted_triceps_dip': 'Віджимання з вагою на трицепс',
      'plank': 'Планка',
      'front_plank': 'Передня планка',
      'side_plank': 'Бокова планка',
      'crunch': 'Скручування',
      'sit_up': 'Підйом корпусу',
      'cable_crunch': 'Скручування в блоці',
      'russian_twist': 'Російські скручування',
      'bicycle_crunch': 'Велосипед',
      'hanging_leg_raise': 'Підйом ніг у висі',
      'wrist_curl': 'Згинання запʼястя',
      'reverse_wrist_curl': 'Зворотне згинання запʼястя',
      'neck_flexion': 'Згинання шиї',
    },
    GymLanguage.en: {
      'bench_press': 'Bench Press',
      'incline_press': 'Incline Press',
      'dumbbell_fly': 'Dumbbell Fly',
      'squat': 'Squat',
      'leg_press': 'Leg Press',
      'lunge': 'Lunge',
      'leg_extension': 'Leg Extension',
      'deadlift': 'Deadlift',
      'romanian_deadlift': 'Romanian Deadlift',
      'hip_thrust': 'Hip Thrust',
      'glute_bridge': 'Glute Bridge',
      'leg_curl': 'Leg Curl',
      'overhead_press': 'Overhead Press',
      'lateral_raise': 'Lateral Raise',
      'rear_delt_fly': 'Rear Delt Fly',
      'barbell_row': 'Barbell Row',
      'pull_up': 'Pull-Up',
      'lat_pulldown': 'Lat Pulldown',
      'seated_row': 'Seated Row',
      'biceps_curl': 'Biceps Curl',
      'hammer_curl': 'Hammer Curl',
      'triceps_pushdown': 'Triceps Pushdown',
      'skull_crusher': 'Skull Crusher',
      'plank': 'Plank',
      'cable_crunch': 'Cable Crunch',
    },
  };

  static const _muscleNames = {
    GymLanguage.uk: {
      'Chest': 'Груди',
      'Quads': 'Квадрицепси',
      'Posterior': 'Задній ланцюг',
      'Shoulders': 'Плечі',
      'Back': 'Спина',
      'Glutes': 'Сідниці',
      'Hamstrings': 'Біцепс стегна',
      'Biceps': 'Біцепс',
      'Triceps': 'Трицепс',
      'Core': 'Прес',
      'Calves': 'Ікри',
      'Forearms': 'Передпліччя',
      'Neck': 'Шия',
      'Custom': 'Свої',
      'Unknown': 'Невідомо',
    },
    GymLanguage.en: {
      'Chest': 'Chest',
      'Quads': 'Quads',
      'Posterior': 'Posterior',
      'Shoulders': 'Shoulders',
      'Back': 'Back',
      'Glutes': 'Glutes',
      'Hamstrings': 'Hamstrings',
      'Biceps': 'Biceps',
      'Triceps': 'Triceps',
      'Core': 'Core',
      'Calves': 'Calves',
      'Forearms': 'Forearms',
      'Neck': 'Neck',
      'Custom': 'Custom',
      'Unknown': 'Unknown',
    },
  };

  String t(String key) => _values[language]![key] ?? key;

  String exerciseName(String id, String fallback) {
    final explicit = _exerciseNames[language]![id];
    if (explicit != null) {
      return explicit;
    }
    if (language == GymLanguage.uk) {
      return translateExerciseNameUk(fallback);
    }
    return fallback;
  }

  String muscleName(String muscle) {
    return _muscleNames[language]![muscle] ?? muscle;
  }

  String catalogAttribute(String value) {
    final cleaned = value.replaceAll('_', ' ').trim();
    if (cleaned.isEmpty || language == GymLanguage.en) {
      return cleaned;
    }
    if (cleaned.contains(',')) {
      return cleaned
          .split(',')
          .map((part) => catalogAttribute(part))
          .where((part) => part.isNotEmpty)
          .join(', ');
    }

    final key = cleaned.toLowerCase();
    const uk = {
      'body weight': 'Власна вага',
      'dumbbell': 'Гантелі',
      'barbell': 'Штанга',
      'cable': 'Кросовер',
      'band': 'Резинка',
      'resistance band': 'Резинка',
      'lever': 'Тренажер',
      'machine': 'Тренажер',
      'smith machine': 'Сміт',
      'sled machine': 'Платформа',
      'kettlebell': 'Гиря',
      'upper arms': 'Руки',
      'upper legs': 'Ноги',
      'lower legs': 'Ікри',
      'waist': 'Прес',
      'back': 'Спина',
      'chest': 'Груди',
      'shoulders': 'Плечі',
      'cardio': 'Кардіо',
      'strength': 'Силова',
      'stretching': 'Розтяжка',
      'weighted': 'З вагою',
      'assisted': 'З підтримкою',
      'custom': 'Своя',
      'bodyweight': 'Власна вага',
      'biceps': 'Біцепс',
      'triceps': 'Трицепс',
      'forearms': 'Передпліччя',
      'glutes': 'Сідниці',
      'hamstrings': 'Біцепс стегна',
      'quads': 'Квадрицепси',
      'weight reps': 'Вага + повтори',
      'reps only': 'Тільки повтори',
      'duration': 'Час',
    };
    return uk[key] ?? cleaned;
  }
}
